In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import plotly.express as px

# Data Loading and Understanding

In [ ]:
# Upload the csv file
life = pd.read_csv('/content/data.csv')
# Take a quick overview of the data
life.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015.0,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014.0,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013.0,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012.0,Developing,59.5,272.0,69,0.01,NaN,67.0,2787,...,67.0,8.52,67.0,0.1,NaN,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011.0,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,NaN,NaN
5,Afghanistan,2010.0,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009.0,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008.0,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007.0,Developing,57.5,295.0,82,0.02,NaN,63.0,1141,...,63.0,6.73,63.0,0.1,NaN,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006.0,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,...,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

In [ ]:
# Unify columns name formats
life.columns = life.columns.str.lower().str.strip().str.replace(' ','_')

In [ ]:
# Exploring the data
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country                          2938 non-null   object
 1   year                             2909 non-null   float64
 2   status                           2938 non-null   object
 3   life_expectancy                  2928 non-null   float64
 4   adult_mortality                  2928 non-null   float64
 5   infant_deaths                    2938 non-null   int64
 6   alcohol                          2294 non-null   float64
 7   percentage_expenditure           2645 non-null   float64
 8   hepatitis_b                      1972 non-null   float64
 9   measles                          2938 non-null   int64
 10  bmi                              2904 non-null   float64
 11  under-five_deaths                2938 non-null   int64
 12  polio                            2919 non-null   float64
 13  total_expenditure                2712 non-null   float64
 14  diphtheria                       2919 non-null   float64
 15  hiv/aids                         2938 non-null   float64
 16  gdp                              2242 non-null   float64
 17  population                       2286 non-null   float64
 18  thinness__1-19_years             2904 non-null   float64
 19  thinness_5-9_years               2904 non-null   float64
 20  income_composition_of_resources  2638 non-null   float64
 21  schooling                        2634 non-null   float64
dtypes: float64(17), int64(3), object(2)
memory usage: 505.1+ KB

In [ ]:
# Display summary statistics for numerical columns
life.describe()

,year,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
count,2909.000000,2928.000000,2928.000000,2938.000000,2294.000000,2645.000000,1972.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2242.000000,2.286000e+03,2904.000000,2904.000000,2638.000000,2634.000000
mean,2007.510141,69.224932,164.796448,30.303948,4.806203,724.042649,81.422921,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7395.259640,1.275338e+07,4.839704,4.870317,0.627247,11.997912
std,4.612977,9.523867,124.292079,117.926501,4.132550,1972.908795,24.679984,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14221.705442,6.101210e+07,4.420195,4.508882,0.209930,3.365215
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,1.000000,4.877350,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,460.023839,1.957932e+05,1.600000,1.500000,0.492000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.970000,66.022363,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1772.961675,1.386542e+06,3.300000,3.300000,0.675500,12.400000
75%,2012.000000,75.700000,228.000000,22.000000,8.137500,430.876979,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5873.386491,7.420359e+06,7.200000,7.200000,0.778750,14.275000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

# Data Cleaning

In [ ]:
# Fixing inconsistent column name (thinness__1-19_years to thinness_10-19_years)
column_lst = list(life.columns)
column_lst[18]=column_lst[18].replace('__1','_10')
life.columns=column_lst

In [ ]:
# Drop unnecessary columns
life = life.drop(columns=['infant_deaths','under-five_deaths'])

In [ ]:
# Checking for nulls
null_check=(life.isna().sum().sort_values(ascending=False)/life.shape[0])*100
null_check

hepatitis_b                        32.879510
gdp                                23.689585
population                         22.191967
alcohol                            21.919673
schooling                          10.347175
income_composition_of_resources    10.211028
percentage_expenditure              9.972771
total_expenditure                   7.692308
thinness_5-9_years                  1.157250
thinness_10-19_years                1.157250
bmi                                 1.157250
year                                0.987066
diphtheria                          0.646698
polio                               0.646698
life_expectancy                     0.340368
adult_mortality                     0.340368
status                              0.000000
country                             0.000000
measles                             0.000000
hiv/aids                            0.000000
dtype: float64

In [ ]:
# Drop nulls from life_expectancy column as it is the target column and null percentage is very low
life.dropna(subset='life_expectancy',inplace=True)

In [ ]:
# Creating a list of columns containing nulls only
col_with_null = null_check[null_check>0]
null_col_list = list(col_with_null.index)
null_col_list

['hepatitis_b',
 'gdp',
 'population',
 'alcohol',
 'schooling',
 'income_composition_of_resources',
 'percentage_expenditure',
 'total_expenditure',
 'thinness_5-9_years',
 'thinness_10-19_years',
 'bmi',
 'year',
 'diphtheria',
 'polio',
 'life_expectancy',
 'adult_mortality']

In [ ]:
# Remove categorical columns from this list (we consider year here as a category so we remove it)
null_col_list.remove('year')
null_col_list
# We must remeber that we have removed year column but we stil need to deal with missing values but in a way differ from those in the list

['hepatitis_b',
 'gdp',
 'population',
 'alcohol',
 'schooling',
 'income_composition_of_resources',
 'percentage_expenditure',
 'total_expenditure',
 'thinness_5-9_years',
 'thinness_10-19_years',
 'bmi',
 'diphtheria',
 'polio',
 'life_expectancy',
 'adult_mortality']

In [ ]:
# Creating user-defined function to calculate outlier percentage
def outlier_percent(s):
  s=s.dropna()
  q1 = s.quantile(0.25)
  q3= s.quantile(0.75)
  iqr = q3-q1
  lower = q1-(1.5*iqr)
  upper = q3+(1.5*iqr)
  outlier = s[(s<lower)|(s>upper)]
  return round((len(outlier)/len(s))*100,2)

In [ ]:
# Using the outlier_percent function to detect outliers percentage in each column
# Note all columns in the provided list are numeric
outlier_report = {col:outlier_percent(life[col])
                    for col in null_col_list}
outlier_report

{'hepatitis_b': 9.93,
 'gdp': 14.53,
 'population': 12.87,
 'alcohol': 0.0,
 'schooling': 1.56,
 'income_composition_of_resources': 4.59,
 'percentage_expenditure': 13.28,
 'total_expenditure': 1.11,
 'thinness_5-9_years': 3.35,
 'thinness_10-19_years': 3.07,
 'bmi': 0.0,
 'diphtheria': 10.21,
 'polio': 9.56,
 'life_expectancy': 0.34,
 'adult_mortality': 2.8}

In [ ]:
# Visualize distribution of columns in null_col_list
for i in null_col_list:
  fig = px.histogram(life,x=i)
  fig.show()

In [ ]:
# After studying distribution and outlier percentages we divided the columns to be imputed in to 2 lists one to be filled with median and the other with mean
median_fill = ['hepatitis_b','gdp','population','percentage_expenditure','thinness_5-9_years','thinness_10-19_years','diphtheria','polio','adult_mortality']
mean_fill = ['schooling','total_expenditure','bmi','income_composition_of_resources']

In [ ]:
# Chech string columns
life['country'].unique()
life['status'].unique()

array(['Developing', 'Developed'], dtype=object)

In [ ]:
# Fix inconsistent column (country)
life['country']=life['country'].str.strip()
life['country']=life['country'].str.title()
life['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua And Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State Of)', 'Bosnia And Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte D'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       "Democratic People'S Republic Of Korea",
       'Democratic Republic Of The Congo', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic Of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People'S Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia (Federated States Of)',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic Of Korea', 'Republic Of Moldova',
       'Romania', 'Russian Federation', 'Rwanda', 'Saint Lucia',
       'Saint Vincent And The Grenadines', 'Samoa',
       'Sao Tome And Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The Former Yugoslav Republic Of Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad And Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom Of Great Britain And Northern Ireland',
       'United Republic Of Tanzania', 'United States Of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic Of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
# Creating dict to group countries in our dataset with continent (This categorization is done using Gemini AI)
continents = {
    'Africa': [
        'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi',
        "Côte D'Ivoire", 'Cabo Verde', 'Cameroon', 'Central African Republic',
        'Chad', 'Comoros', 'Congo', 'Democratic Republic Of The Congo',
        'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
        'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya',
        'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Malaysia',
        'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia',
        'Niger', 'Nigeria', 'Rwanda', 'Sao Tome And Principe', 'Senegal',
        'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan',
        'Sudan', 'Swaziland', 'Togo', 'Tunisia', 'Uganda',
        'United Republic Of Tanzania', 'Zambia', 'Zimbabwe'
    ],
    'Asia': [
        'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh',
        'Bhutan', 'Brunei Darussalam', 'Cambodia', 'China', 'Cyprus',
        'Georgia', 'India', 'Indonesia', 'Iran (Islamic Republic Of)',
        'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait',
        'Kyrgyzstan', "Lao People'S Democratic Republic", 'Lebanon',
        'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
        'Philippines', 'Qatar', 'Republic Of Korea',
        "Democratic People'S Republic Of Korea", 'Saudi Arabia', 'Singapore',
        'Sri Lanka', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
        'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates',
        'Uzbekistan', 'Viet Nam', 'Yemen'
    ],
    'Europe': [
        'Albania', 'Austria', 'Belarus', 'Belgium', 'Bosnia And Herzegovina',
        'Bulgaria', 'Croatia', 'Czechia', 'Denmark', 'Estonia', 'Finland',
        'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland',
        'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Montenegro',
        'Netherlands', 'Norway', 'Poland', 'Portugal', 'Republic Of Moldova',
        'Romania', 'Russian Federation', 'Serbia', 'Slovakia', 'Slovenia',
        'Spain', 'Sweden', 'Switzerland',
        'The Former Yugoslav Republic Of Macedonia', 'Ukraine',
        'United Kingdom Of Great Britain And Northern Ireland'
    ],
    'North America': [
        'Antigua And Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada',
        'Costa Rica', 'Cuba', 'Dominican Republic', 'El Salvador', 'Grenada',
        'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua',
        'Panama', 'Saint Lucia', 'Saint Vincent And The Grenadines',
        'Trinidad And Tobago', 'United States Of America'
    ],
    'South America': [
        'Argentina', 'Bolivia (Plurinational State Of)', 'Brazil', 'Chile',
        'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
        'Uruguay', 'Venezuela (Bolivarian Republic Of)'
    ],
    'Oceania': [
        'Australia', 'Fiji', 'Kiribati', 'Micronesia (Federated States Of)',
        'New Zealand', 'Papua New Guinea', 'Samoa', 'Solomon Islands',
        'Tonga', 'Vanuatu'
    ]
}

In [ ]:
# Adding continent column to the dataframe
continent_country = {country:continent for continent,countries in continents.items() for country in countries}
life['continent']=life['country'].map(continent_country)

In [ ]:
life=life[~(life['country']=='Israel')]

In [ ]:
# Verifying if each country has a record for each year from 2000 to 2015
country_year = life['country'].value_counts().reset_index()
country_year[(country_year['count']<16) | (country_year['count']>16)]
# Total number of years in this dataset is 16 so as we see here each country has 16 record one for each year

Empty DataFrame
Columns: [country, count]
Index: []

In [ ]:
# Impute columns we have prepared before with median
for col in median_fill:
  life[col]=life.groupby('country')[col].transform(lambda x: x.fillna(x.median()))

In [ ]:
# Impute columns we have prepared before with mean
for col in mean_fill:
  life[col]=life.groupby('country')[col].transform(lambda x: x.fillna(x.mean()))

In [ ]:
# Check for nulls again
life.isna().sum().sort_values(ascending=False)

population                         640
alcohol                            638
gdp                                400
schooling                          160
income_composition_of_resources    160
hepatitis_b                        144
thinness_5-9_years                  32
total_expenditure                   32
bmi                                 32
thinness_10-19_years                32
year                                29
status                               0
country                              0
adult_mortality                      0
life_expectancy                      0
percentage_expenditure               0
measles                              0
diphtheria                           0
polio                                0
hiv/aids                             0
continent                            0
dtype: int64

In [ ]:
# Drop missing rows that are common in [bmi,thinness_10-19_years, thinness_5-9_years]
life.dropna(subset=['bmi'],axis=0,inplace=True)

In [ ]:
# Creating a function to clean year column based on what we observed
def y_fill(s):
  for i in range(len(s)):
    if i==0:
      if pd.isna(s.iloc[i]):
        s.iloc[i]=s.iloc[i+1]+1
    elif i==max(range(len(s))):
      if pd.isna(s.iloc[i]):
        s.iloc[i]=s.iloc[i-1]-1
    else:
      if pd.isna(s.iloc[i]) and pd.isna(s.iloc[i+1]):
        s.iloc[i]=s.iloc[i-1]-1
      elif pd.isna(s.iloc[i]):
        s.iloc[i]=np.mean([s.iloc[i-1],s.iloc[i+1]])
  return s

In [ ]:
# Clean year column using the function we have created
life['year']=life.groupby('country')['year'].transform(y_fill)

In [ ]:
# Check for nulls after cleaning
life.isna().sum().sort_values(ascending=False)

population                         640
alcohol                            616
gdp                                400
schooling                          160
income_composition_of_resources    160
hepatitis_b                        144
total_expenditure                   32
adult_mortality                      0
year                                 0
country                              0
life_expectancy                      0
status                               0
percentage_expenditure               0
diphtheria                           0
polio                                0
bmi                                  0
measles                              0
thinness_10-19_years                 0
hiv/aids                             0
thinness_5-9_years                   0
continent                            0
dtype: int64

In [ ]:
# Studying correlation between columns that represent socioeconomic status
num = life.select_dtypes(include='number')
corr_col = ['population','alcohol','gdp','schooling','income_composition_of_resources','total_expenditure']
num.corr().loc[corr_col, corr_col]

,population,alcohol,gdp,schooling,income_composition_of_resources,total_expenditure
population,1.000000,-0.044534,-0.026132,-0.034543,-0.010074,-0.082898
alcohol,-0.044534,1.000000,0.373221,0.570623,0.483653,0.322343
gdp,-0.026132,0.373221,1.000000,0.454046,0.462413,0.131968
schooling,-0.034543,0.570623,0.454046,1.000000,0.783935,0.262106
income_composition_of_resources,-0.010074,0.483653,0.462413,0.783935,1.000000,0.163108
total_expenditure,-0.082898,0.322343,0.131968,0.262106,0.163108,1.000000

In [ ]:
# Studying correlation between columns that describe immunizations
corr_imm = ['polio','diphtheria']
num.corr().loc[corr_imm,'hepatitis_b']

polio         0.471702
diphtheria    0.545163
Name: hepatitis_b, dtype: float64

In [ ]:
# Dropping columns that have weak correlation and will not be efficiently imputed using KNN imputation and will not affect our analysis
life.drop(columns=['population','total_expenditure'],inplace=True)

In [ ]:
# Impute using KNN

# Import necessary tools
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

# Prepare list of columns to be imputed in 2 lists as we discussed before after studying correlation
socio_econ = ['alcohol','gdp','schooling','income_composition_of_resources']
immunz = ['polio','diphtheria','hepatitis_b']

# Standardizing numbers in columns to help the model impute correctly
scaling_se = StandardScaler()
socio_econ_scaled = scaling_se.fit_transform(life[socio_econ])
scaling_im = StandardScaler()
immunz_scaled = scaling_im.fit_transform(life[immunz])

# Impute the columns using KNN
imput = KNNImputer(n_neighbors=5)
socio_econ_imputed = imput.fit_transform(socio_econ_scaled)
immunz_imputed = imput.fit_transform(immunz_scaled)

# Inverse standardized columns to get back to their orginal values
life[socio_econ]=scaling_se.inverse_transform(socio_econ_imputed)
life[immunz]= scaling_im.inverse_transform(immunz_imputed)

In [ ]:
# Check for null after KNN imputation
life.isna().sum()

country                            0
year                               0
status                             0
life_expectancy                    0
adult_mortality                    0
alcohol                            0
percentage_expenditure             0
hepatitis_b                        0
measles                            0
bmi                                0
polio                              0
diphtheria                         0
hiv/aids                           0
gdp                                0
thinness_10-19_years               0
thinness_5-9_years                 0
income_composition_of_resources    0
schooling                          0
continent                          0
dtype: int64

# Analysis

Correlation Analysis

In [ ]:
# Studying correlation between different factors in our dataset (Moderate to Strong correlations)
num_clean= life.select_dtypes(include='number')
corr_matrix = num_clean.corr()
strong_corr = corr_matrix[((corr_matrix>0.5) & (corr_matrix<1)) | ((corr_matrix<-0.5) & (corr_matrix>-1))]
px.imshow(strong_corr.round(2), text_auto=True,width=1000, height=800,title='Moderate to Strong Correlated Factors').show()

In [ ]:
# Studying factors affecting our target column (Life Expectancy)
life_exp_corr = num_clean['life_expectancy']
px.imshow(num_clean.corrwith(life_exp_corr).sort_values(ascending=False).to_frame().round(2) , text_auto=True, width=1000, height=800, title='Correlation with Life Expectancy').show()

**Observations:**
  

*   Top 3 factors positively affecting Life Expectancy are: Schooling, Income Composition of Resources and BMI.
*   Top 3 factors negatively affecting Life Expectancy are Thinness, HIV/AIDS and Adult Mortality.

In [ ]:
# Display percentage of developed vs developing countries
status_percent =px.pie(life.groupby('status')['country'].nunique().reset_index(), names='status', values='country')
status_percent.update_traces(textinfo='percent+label', textposition='inside', showlegend=False)

In [ ]:
# Visualizing correlation between GDP and Life Expectancy segmented by country status
px.scatter(life,x='life_expectancy',y='gdp',color='status',trendline='ols',
           labels={'gdp':'GDP','life_expectancy':'Life Expectancy','status':'Status'},
           title='Correlation between GDP and Life Expectancy by Country Status')

In [ ]:
# Visualizing correlation between GDP and BMI segmented by country status
px.scatter(life,x='gdp',y='bmi',color='status',trendline='ols',
           labels={'bmi':'BMI','gdp':'GDP','status':'Status'},
           title='Correlation between GDP and BMI by Country Status')

In [ ]:
# Visualizing correlation between GDP and Thinness(5-9 Years) segmented by country status
px.scatter(life,x='gdp',y='thinness_5-9_years',color='status',trendline='ols',
           labels={'gdp':'GDP','thinness_5-9_years':'Thinness(5-9 Years)','status':'Status'},
           title='Correlation between GDP and Thinness(5-9 Years) by Country Status')

In [ ]:
# Visualizing correlation between GDP and Thinness(10-19 Years) segmented by country status
px.scatter(life,x='gdp',y='thinness_10-19_years',color='status',trendline='ols',
           labels={'gdp':'GDP','thinness_10-19_years':'Thinness(10-19 Years)','status':'Status'},
           title='Correlation between GDP and Thinness(10-19 Years) by Country Status')

In [ ]:
# Visualizing correlation between GDP and Percentage Expenditure segmented by country status
px.scatter(life,x='gdp',y='percentage_expenditure',color='status',trendline='ols',
           labels={'gdp':'GDP','percentage_expenditure':'Percentage Expenditure', 'status':'Status'},
           title='Correlation between GDP and Percentage Expenditure by Country Status')

**Observation:**

GDP didn't appear as a significant influencer on Life Expectancy
but after further it is observed that GDP can be a significant influencer
in developed countries as developing countries have other priorities which
appear to be more important than healthcare such as food, when GDP increase
in developing countries thinness and BMI increase while in developed countries
they remain nearly unchanged

In [ ]:
# Create new feature to calculate health expenditure percentage from GDP
life['expenditure_percent_from_gdp']=(life['percentage_expenditure']/life['gdp'])*100

In [ ]:
# Display the average health expenditure percentage from GDP for each country status
status_exp_percent = life.groupby('status')['expenditure_percent_from_gdp'].mean().round(2).reset_index()
status_exp_percent_pie = px.pie(status_exp_percent,names='status',values='expenditure_percent_from_gdp',
                                title='Average Health Expenditure Percentage from GDP by Country Status')
status_exp_percent_pie.update_traces(textinfo='value+label',showlegend=False)

**Observation:**

Health expenditure percentage from GDP in developed countries is on average greater than that of developing by nearly 3% which supports our observation

In [ ]:
# Visualizing correlation between Life Expectancy and Schooling segmented by country status
px.scatter(life,x='life_expectancy',y='schooling',color='status',trendline='ols',
            labels={'life_expectancy':'Life Expectancy','schooling':'Schooling','status':'Status'},
           title='Correlation between Life Expectancy and Schooling by Country Status')

In [ ]:
# Visualizing correlation between Life Expectancy and Income Composition of Resources segmented by country status
px.scatter(life,x='life_expectancy',y='income_composition_of_resources',color='status',trendline='ols',
           labels={'life_expectancy':'Life Expectancy','income_composition_of_resources':'Income Composition of Resources','status':'Status'},
           title='Correlation between Life Expectancy and Income Composition of Resources by Country Status')

**Observation:**
*   Both Schooling and Income Composition of Resources have strong positive correlation with Life Expectancy.
*   Each of them appear to have both direct and indirect effect on Life Expectancy.
*   Schooling affects Income Composition of Resources meaning it has also indirect effect on Life Expectancy and same applies for Income Composition of Resources.

In [ ]:
# Visualizing Correlation between Life Expectancy and Adult Mortality by Country Status
px.scatter(life,x='life_expectancy',y='adult_mortality',trendline='ols',color='status',
           labels={'life_expectancy':'Life Expectancy','adult_mortality':'Adult Mortality','status':'Status'},
           title='Correlation between Life Expectancy and Adult Mortality by Country Status')

In [ ]:
# Visualizing Correlation between Measles and Adult Mortality by Country Status
px.scatter(life,x='measles',y='adult_mortality',color='status',trendline='ols',
           labels={'measles':'Measles','adult_mortality':'Adult Mortality','status':'Status'},
           title='Correlation between Measles and Adult Mortality by Country Status')

In [ ]:
# Visualizing Correlation between Schooling and Adult Mortality by Country Status
px.scatter(life,x='schooling',y='adult_mortality',color='status',trendline='ols',
           labels={'schooling':'Schooling','adult_mortality':'Adult Mortality','status':'Status'},
           title='Correlation between Schooling and Adult Mortality by Country Status')

In [ ]:
# Visualizing Correlation between Income Composition of Resources and Adult Mortality by Country Status
px.scatter(life,x='income_composition_of_resources',y='adult_mortality',color='status',trendline='ols',
           labels={'income_composition_of_resources':'Income Composition of Resources','adult_mortality':'Adult Mortality','status':'Status'},
           title='Correlation between Income Composition of Resources and Adult Mortality by Country Status')

**Observation:**
*   Life Expectancy decrease when Adult Mortality increase.
*   Adult Mortality appears to be affected by Schooling and Income Composition of Resources, it decreases by increase of Schooling and/or Income Composition of Resources.

In [ ]:
# Visualizing Correlation between Life Expectancy and vaccination rates segmented by country status
vaccine = ['hepatitis_b','polio','diphtheria']
for i in vaccine:
  figs= px.scatter(life,x='life_expectancy',y=i,color='status',trendline='ols',
                   labels={'life_expectancy':'Life Expectancy',i:i.capitalize(),'status':'Status'},
                   title=f'Correlation between Life Expectancy and {i.capitalize()} by Country Status')
  figs.show()

**Observation:**
*   Life Expectancy is affected by vaccinations.
*   It is clear that when vaccination rates increase life expectancy increase mainly in developing countries.
*   In developed countries life Expectancy appear nearly unchanged by vaccination rates, suggesting that hygiene and clean surrounding environment is linked to decrease in microbial spread which in turns may decrease the need for vaccination unlike developing countries.

In [ ]:
# Visualizing Correlation between GDP and vaccination rates segmented by country status
for i in vaccine:
  figs= px.scatter(life,x='gdp',y=i,color='status',trendline='ols',
                   labels={'gdp':'GDP',i:i.capitalize(),'status':'Status'},
                   title=f'Correlation between GDP and {i.capitalize()} by Country Status')
  figs.show()

**Observation:**

In developed countries vaccination rates appear not to be affected by increase in GDP unlike developing ones.

In [ ]:
# Visualizing Correlation between Life Expectancy and socioeconomical features segmented by country status
for i in socio_econ[2:]:
  fig2=px.scatter(life,x='gdp',y=i,color='status',trendline='ols',
                  title=f'Correlation between GDP and {i} by Country Status')
  fig2.show()

**Observation:**

In developed countries nearly there is no correlation between GDP and both Schooling/Income Composition of Resources, however a significant positive correlation is clear in developing ones.

In [ ]:
# GDP contribution by country status from total GDP
gdp_per_status = life.groupby('status')['gdp'].sum().sort_values(ascending=False).reset_index().round(2)
gdp_per_status_pie = px.pie(gdp_per_status,names='status',values='gdp',hole=0.5,title='Share of Country Status From Total GDP')
gdp_per_status_pie.update_traces(textinfo='percent+label',showlegend=False)

**Conclusion:**
*   We can conclude from the previous analysis that GDP is the key influncer that affects Life Expectancy.
*   In developed countries about 10% on average from GDP goes to healthcare expenditure, putting in considerations that those countries have higher GDP.
*   In developing countries larger portion of GDP is spent on food which is suggested to be a priority in those countries, however in those countries a significant positive correlation appears between GDP and both schooling and income composition of resources.
*   Schooling and Income Composition of Resources strongly correlate with higher Life Expectancy.
*   So while not spending higher percentage in healthcare expenditure
developing countries spend more on schooling, income and resources which in turns increase Life Expectancy.

Time Series Anaysis

In [ ]:
# Visualizing trend of average life expectancy
life_ex_trend = life.groupby(['year'])['life_expectancy'].mean().sort_index().reset_index()
px.line(life_ex_trend,x='year',y='life_expectancy',labels={'year':'Year','life_expectancy':'Life Expectancy'},title='Average Life Expectancy Trend by Year').show()

In [ ]:
# Visualizing Average GDP trend by Year segmented by country status
gdp_per_year = life.groupby(['year','status'])['gdp'].mean().sort_index().reset_index()
px.line(gdp_per_year,x='year',y='gdp',color='status',
        labels={'gdp':'GDP','year':'Year','status':'Status'},
                title='Average GDP trend by Year')

In [ ]:
# Visualizing trend of Expenditure Percent From GDP
expend_gdp_percent = life[life['year']!=2015].groupby(['year','status'])['expenditure_percent_from_gdp'].mean().sort_index().reset_index()
px.line(expend_gdp_percent,x='year',y='expenditure_percent_from_gdp',color='status',
        labels={'year':'Year','expenditure_percent_from_gdp':'Expenditure Percent From GDP','status':'Status'},
        title='Expenditure Percent From GDP Trend by Year')

In [ ]:
# Visualizing average schooling trend
schooling_trend = life.groupby('year')['schooling'].mean().sort_index().reset_index()
px.line(schooling_trend,x='year',y='schooling',title='Average Schooling Trend').update_layout(xaxis_title='Year',yaxis_title='Schooling')

In [ ]:
# Visualizing average Income Composition of Resources trend
income_trend = life.groupby('year')['income_composition_of_resources'].mean().sort_index().reset_index()
px.line(income_trend,x='year',y='income_composition_of_resources',title='Average Income Composition of Resources Trend').update_layout(
    xaxis_title='Year',yaxis_title='Income Composition of Resources'
)

In [ ]:
# Visualizing average adult mortality trend
adult_mortality_trend = life.groupby('year')['adult_mortality'].mean().sort_index().reset_index()
px.line(adult_mortality_trend,x='year',y='adult_mortality',title='Average Adult Mortality Trend').update_layout(
    xaxis_title='Year',yaxis_title='Adult Mortality'
)

**Conclusion:**
*   Life Expectancy increased over time.
*   There is a rising trend in both Schooling and Income Composition of Resources while a downward trend is observed in Adult Mortality.
*   These factors are strongly correlated to Life Expectancy which led to its increase.
*   GDP shows slight increase over time however increase in Schooling and Income Composition of Resources appears to be significant.
*   This suggests that GDP is not only the factor that affect Schooling and Income Composition of Resources other factors can do, such as money that comes from abroad (Remittances, Foreign Investment, Foreign Aid, External Loans).
*   This reveals that sources of money other than GDP are as important as GDP in increasing Life Expectancy.

Regional Analysis

In [ ]:
# Visualizing average life expectancy by continent
life_expectancy_per_continent = life.groupby('continent')['life_expectancy'].mean().round(2).sort_values().reset_index()
px.histogram(life_expectancy_per_continent,x='life_expectancy',y='continent',text_auto=True,title='Average Life Expectancy by Continent').update_layout(
    xaxis_title='Life Expectancy',yaxis_title='Continent'
)

In [ ]:
# Visualizing country count per continent
country_count_per_cont = life.groupby(['continent','status'])['country'].nunique().reset_index().sort_values(by='country',ascending=False)
px.histogram(country_count_per_cont,x='continent',y='country',color='status', text_auto=True,barmode='group',
             title='Country Count Per Continent').update_layout(xaxis_title='Continent',yaxis_title='Country')

In [ ]:
# Visualizing Average GDP by Continent
continent_gdp = life.groupby('continent')['gdp'].mean().sort_values(ascending=False).reset_index()
px.histogram(continent_gdp,x='continent',y='gdp',
             title='Average GDP by Continent').update_layout(yaxis_title='GDP',xaxis_title='Continent')

In [ ]:
# Visualizing average thinness in 10-19 year by continent
thin1019_per_cont = life.groupby('continent')['thinness_10-19_years'].mean().sort_values().reset_index().round(2)
px.histogram(thin1019_per_cont,y='continent',x='thinness_10-19_years',text_auto=True,title='Average Thinness (10-19 Years) by Country').update_layout(
    xaxis_title='Thinness (10-19 Years)',yaxis_title='Continent'
)

In [ ]:
# Visualizing average thinness in 5-9 year by continent
thin59_per_cont=life.groupby('continent')['thinness_5-9_years'].mean().sort_values().reset_index().round(2)
px.histogram(thin59_per_cont,y='continent',x='thinness_5-9_years',text_auto=True,title='Average Thinness (5-9 Years) by Country').update_layout(
    xaxis_title='Thinness (5-9 Years)',yaxis_title='Continent'
)

In [ ]:
# Visualizing average income composition of resources by continent
hdi_per_cont=life.groupby('continent')['income_composition_of_resources'].mean().sort_values().reset_index().round(2)
px.histogram(hdi_per_cont,y='continent',x='income_composition_of_resources',text_auto=True,title='Average Income Composition of Resources by Continent').update_layout(
    xaxis_title='Income Composition of Resources',yaxis_title='Continent'
)

In [ ]:
# Visualizing average schooling by continent
school_per_cont = life.groupby('continent')['schooling'].mean().sort_values().reset_index().round(2)
px.histogram(school_per_cont,y='continent',x='schooling',text_auto=True,title='Average Schooling by Continent').update_layout(
    xaxis_title='Schooling',yaxis_title='Continent'
)

In [112]:
# Top 10 countries by life expectancy
country_per_lifeex =life.groupby(['country','status'])['life_expectancy'].mean().sort_values(ascending=False).reset_index()
px.histogram(country_per_lifeex.head(10),x='country',y='life_expectancy',color='status',title='Top 10 Countries by Life Expectancy',color_discrete_map={'Developed': 'blue', 'Developing': 'red'}).update_layout(
    xaxis_title='Country',yaxis_title='Life Expectancy',legend_title='Status'
)

In [ ]:
# Bottom 10 countries by life expectancy
px.histogram(country_per_lifeex.tail(10),x='country',y='life_expectancy',color='status',title='Bottom 10 Countries by Life Expectancy', color_discrete_map={'Developed': 'blue', 'Developing': 'red'}).update_layout(
    xaxis_title='Country',yaxis_title='Life Expectancy',legend_title='Status'
    )

In [139]:
# Studying GDP ranking by country
gdp_ranking = life.groupby(['country','status'])['gdp'].mean().sort_values(ascending=False).head(20).reset_index()
gdp_ranking

        country      status           gdp
0   Switzerland   Developed  59756.827136
1    Luxembourg   Developed  51535.955034
2       Denmark   Developed  40142.219536
3         Qatar  Developing  39042.115586
4   Netherlands   Developed  38377.886732
5        Kuwait  Developing  34538.934246
6     Singapore   Developed  34205.324551
7       Ireland   Developed  33835.272005
8     Australia   Developed  33004.637223
9       Austria   Developed  31388.305574
10       Canada  Developing  29444.549947
11      Iceland   Developed  29163.829773
12       Sweden   Developed  26969.777652
13       France  Developing  26465.551381
14      Finland  Developing  26162.957449
15        Japan   Developed  24892.544784
16       Norway   Developed  23268.731265
17        Italy   Developed  22974.333182
18      Germany   Developed  21866.912517
19      Czechia   Developed  19057.637739

In [143]:
# Studying adult mortality ranking by country
adult_mortality_rank= life.groupby('country')['adult_mortality'].mean().sort_values().head(20).reset_index()
adult_mortality_rank

                                      country  adult_mortality
0                                     Tunisia          18.7500
1                                     Albania          45.0625
2                                     Iceland          49.3750
3                                Saudi Arabia          52.1250
4                                      Cyprus          54.1250
5                                       Italy          54.1875
6                                 Switzerland          55.7500
7                                       Japan          57.1250
8                                        Cuba          57.5625
9                    United States Of America          58.1875
10                                   Portugal          58.8750
11                                     Sweden          59.1875
12                                      Malta          60.7500
13  The Former Yugoslav Republic Of Macedonia          60.8125
14                                Netherlands          61.6250
15                                  Singapore          62.0000
16                                  Australia          63.1875
17                                      Spain          63.6250
18                                      Chile          63.6250
19                                     Canada          64.6250

In [145]:
# Studying income composition of resources ranking by country
HDI_rank=life.groupby('country')['income_composition_of_resources'].mean().sort_values(ascending=False).head(20).reset_index()
HDI_rank

        country  income_composition_of_resources
0        Norway                         0.931438
1     Australia                         0.918125
2   Switzerland                         0.911062
3   Netherlands                         0.901846
4       Denmark                         0.899875
5        Sweden                         0.893000
6        Canada                         0.892429
7       Ireland                         0.891500
8   New Zealand                         0.891200
9       Germany                         0.890385
10      Iceland                         0.886133
11   Luxembourg                         0.880133
12      Belgium                         0.877750
13        Japan                         0.876067
14      Finland                         0.870714
15       France                         0.870563
16    Singapore                         0.866875
17      Austria                         0.862375
18     Slovenia                         0.860437
19        Italy                         0.858062

**Conclusion:**
*   Highest Life Expectancy appears in Europe while Lowest appear in Africa.
*   Europe has significant high GDP compared to other continents followed by Asia however, Asia appear to have low Life Expectancy following Africa.
*   Prevalence of thinness in Asia with low schooling and HDI justifies why Life Expectancy is low regardless relatively high GDP.
*   Count of countries in Asia in our dataset is relatively high compared to other continents (excluding Africa) and it includes 3 developed countries, something which we must put in consideration that justifies the relatively high GDP.
*   Japan appears as the country with highest Life Expectancy despite being in Asia, this may be due to its appearnce in top 20 GDP, adult mortality and HDI but further analysis is needed to detect the root causes using additionl features.